// <auto-generated />
namespace gtv_tele.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editmasteruploaddet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editmasteruploaddet));
        
        string IMigrationMetadata.Id
        {
            get { return "202109070158107_edit-master-upload-det"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
